### ISSUE TITLE
How should duplicate data in import be handled?

### ISSUE THREAD

**Issue by MikeStower** [QAAFI/REMS2020#26]
Currently, all data in the selected file is imported. However, there may be a situation where duplicate information is attempted to be imported (for example, two different information sheets use the same soil type). 

Should the current process be left alone, or should all/some duplicates be ignored upon import?

**Comment by MStowerUQ** [comment]
Observed data should not import duplicates, only new data.

**Comment by jbrider** [comment]
existing observations should also be updated if the data has changed.
Performance is not the priority here - data integrity is.
It would be good to add some sort of history on sample updates - probably not at a low level though.
Maybe a report (table) on number of observations updated, ignored, created on import for each table?
Or maybe by Trait?  TraitImportTable -> TraitID, Date(of update), Added, Updated, Ignored as columns?

**Comment by MStowerUQ** [comment]
There already exists a 'FindMatchingEntity' function for a context, which does a brute force search force of the context for an entity with matching data. This should be sufficient to prevent duplicate data for all the information tables that use the generic import, as they are small enough that performance won't be an issue. For example, if we tried to add a crop called 'Sorghum', it would look through the database, and if it found a crop with that name, exclude that data. 

However, this relies on the assumption that the information about an experiment itself won't be subject to change, and that only the measured data is volatile. Since it depends on directly comparing values, it would be difficult to tell if an entry contains new data, or existing data that has been updated / changed.

Still working on a solution for measured data / custom table importers.
